### ISSUE TITLE
[Bug] Test incorrectly marked as failed when using `waitFor`

### ISSUE THREAD

**Issue by Andrei-Mardale** [storybookjs/test-runner#160]
### Describe the bug

Failed `expect` assertions within `waitFor` cause the test to be marked as failed even if subsequent assertions are successful.

`waitFor` is used as per the [documentation](https://testing-library.com/docs/dom-testing-library/api-async/#waitfor) from `testing-library`
### Steps to reproduce the behavior

Use the following code snippet. DemoTest should be marked as successful.

```
import { Meta, StoryFn } from '@storybook/preact';
import { waitFor } from '@testing-library/preact';
import { h } from 'preact';
import { expect } from '@storybook/jest';

const storyMeta: Meta<void> = {
  title: 'Demo'
};

export default storyMeta;

const DefaultTemplate: StoryFn<void> = () => <div> Story Content</div>;

export const DemoTest: StoryFn<void> = DefaultTemplate.bind({});
DemoTest.play = async () => {
  let counter = 0;

  await waitFor(() => {
    counter += 1;
    expect(counter).toBe(3);
  });

  expect(true).toBe(true);
};
```

### Expected behavior

Tests should allow for failed assertions if those assertions are caught by the test function or handled by methods such as `waitFor`.
Those failed assertions may come from `expect` calls or other similar calls such as `userEvent.click`, etc.

### Screenshots and/or logs
![Screenshot 2022-08-08 at 17 12 15](https://user-images.githubusercontent.com/8865276/183438620-2f586e38-eed9-4050-8b07-8c07fbe93ae2.png)

### Environment

 - Node.js version: [e.g. v12.17.0]
 - NPM version: [e.g. 6.14.4]
 - Browser (if applicable): [e.g. chrome, safari]
 - Browser version (if applicable): [e.g. 22]
 - Device (if applicable): [e.g. iPhone6]

**Comment by gabrielperales** [comment]
I'm having the same issue. In my case, I was waiting for an element to finish an animation and I had to add a fixed amount of ms instead of using the waitFor :(

**Comment by yannbf** [comment]
Hey there, I can confirm this issue happens when using `@testing-library/dom` directly, which is something **we do not recommend**:
<img width="541" alt="image" src="https://github.com/storybookjs/test-runner/assets/1671563/b9d100d2-a89b-43ce-99e5-bd90212a2548">

If you use `@storybook/testing-library` instead, **which we do recommend**, you won't face this issue.
<img width="401" alt="image" src="https://github.com/storybookjs/test-runner/assets/1671563/8c9156a0-be89-4ffb-a4a6-c64be9f8af80">

Please migrate your tests and let us know if you face any issues:
```diff
-import { waitFor } from '@testing-library/preact';
+import { waitFor } from '@storybook/testing-library';
```

Thanks!
