### ISSUE TITLE
[Feature Request] Compatibility with Jest 29

### ISSUE THREAD

**Issue by cprecioso** [storybookjs/test-runner#185]
Jest v29 was recently released ([blog post](https://jestjs.io/blog/2022/08/25/jest-29), [migration guide](https://jestjs.io/docs/upgrading-to-jest29), [changelog](https://github.com/facebook/jest/blob/main/CHANGELOG.md#2900)).
The test runner should have support for it. According to the blog post, it should be a straight-forward upgrade.

**Comment by yannbf** [comment]
Hey @cprecioso thanks for opening this issue.

Unless you really need something from Jest 29 in the context of your tests running via the test runner, you should not need to worry about it anymore. The test runner used to require you to install Jest as a peer dependency, thus the need to have compatible versions of Jest in your project, but now it's contained and it will come with Jest 28 internally since [version 0.7.0](https://github.com/storybookjs/test-runner/releases/tag/v0.7.0), so there's no such thing as compatibility issues anymore.

**Comment by cprecioso** [comment]
Understood, thanks for the explanation!

**Comment by callumacrae** [comment]
There's a workaround for jest's memory leak issues in v29 - https://github.com/facebook/jest/issues/11956

i'm currently unable to use it with storybook/test-runner, so i'm currently getting memory errors on CI 😬

**Comment by skaindl** [comment]
This is really a problem, considering Angular 16 only supports jest-preset-angular 13.1.1, which requires jest 29. I now cannot use the test runner without the following error: 
`ts-jest[versions] (WARN) Version 28.1.3 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=29.0.0 <30.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.`

Please prioritize this very necessary upgrade.

**Comment by yannbf** [comment]
Hey everyone! I'm happy to say that the test-runner now uses Jest 29, please try its beta version here:
[`v0.14.0-next.2`](https://github.com/storybookjs/test-runner/releases/tag/v0.14.0-next.2)

It will be promoted to latest once it has enough feedback regarding its stability. Thank you! <3
