### ISSUE TITLE
[Feature Request] Storybook default tests timeouts must accept overrides

### ISSUE THREAD

**Issue by AthulMuralidhar** [storybookjs/test-runner#300]
### Is your feature request related to a problem? Please describe

So, i have a long running test and I want to be able to override the global timeout defined in the storybook config

### Describe the solution you'd like

the error suggestion says 
```typescript
 thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
```
I would just like this one to work

FYI:  the imports for `jest` looks like this: `import { jest } from "@storybook/jest";`

### Describe alternatives you've considered

- tried messing around with `Parameters` for that particular `Story`
- tried adding await sleep

### Are you able to assist to bring the feature to reality?

yes, I can

### Additional context

Answer is actually maybe? I am not sure if i have enough knowledge to be of help - only been doing storybook for the past 3 months - besides, i'm a golang dev :P

**Comment by kasperstorgaard** [comment]
I think you can eject and override it from there:
https://storybook.js.org/docs/react/writing-tests/test-runner#cli-options

**Comment by staykova-sport-thieme** [comment]
I am experiencing some odd behaviour. I installed test-runner and then ran `yarn test-storybook` so that the smoke-tests run, all tests failed because of a timeout error. I ran the command a couple of more times one after the other and after every run the number of tests that passed increased untill all tests have passed... which is really odd.
The error:
<img width="300" alt="Screenshot 2023-05-31 at 11 28 52" src="https://github.com/storybookjs/test-runner/assets/75254865/dae8b865-c04f-4888-aa14-04bb2dcc207b">
Results after running `test-storybook` several times one after the other, I am missing one screenshot for all failed, 0 passed:
<img width="300" alt="Screenshot 2023-05-31 at 11 28 11" src="https://github.com/storybookjs/test-runner/assets/75254865/3c461b53-8a5c-41ce-9abf-03cb9a912414">
<img width="300" alt="Screenshot 2023-05-31 at 11 28 30" src="https://github.com/storybookjs/test-runner/assets/75254865/f1c4c788-efbc-44d3-be68-839d7e3802f4">
<img width="300" alt="Screenshot 2023-05-31 at 11 28 37" src="https://github.com/storybookjs/test-runner/assets/75254865/41de1d17-8bb2-44f7-b606-693617e75f7e">

**Comment by yannbf** [comment]
Hey everyone! Thanks for opening this issue. I can definitely understand the confusion, thinking that `@storybook/jest` should be used for the timeout. That is not the case. `@storybook/jest` is a helper utility for the browser. Jest configs are overwritten in the test-runner via the test-runner file as perfectly explained by @MaxDNG!

I will update the docs and provide an example for this. Thank you!

**Comment by david-morris** [comment]
@yannbf so there is no way to change the timeout for one test?  That sounds like not-planned rather than completed.

**Comment by vchandran8** [comment]
We are getting sometime the below error and that is not resolving by Jest Config. Is there any recommendation found for overriding the playwright timeout part of testRunner.

page.goto timeout 30000ms exceeded playwright

**Comment by IsaiahByDayah** [comment]
> We are getting sometime the below error and that is not resolving by Jest Config. Is there any recommendation found for overriding the playwright timeout part of testRunner.
> 
> page.goto timeout 30000ms exceeded playwright

Hey @vchandran8  We're running into this too. Wondering if you ever found a solution to your issue?

**Comment by KelvinOm** [comment]
I also experienced this on `v0.19.1`.

**Comment by vivekKodira** [comment]
@yannbf Did you misunderstand the issue? It does seem that tests should be able to override the global configuration but that they are not. The documentation update you've added as a solution still talks about the global override.
