### ISSUE TITLE
[Bug]: Type of canvasElement from getStoryContext is unknown

### ISSUE THREAD

**Issue by unional** [storybookjs/test-runner#436]
### Describe the bug

```ts
import { getStoryContext } from "@storybook/test-runner"

// in postVisit
const storyContext = await getStoryContext(page, context)
storyContext.canvasElement // type unknown should be HTMLElement
``` 

This is caused by:

```ts
interfact StoryContext<TRenderer extends Renderer = Renderer, ...> ... {

  canvasElement: TRenderer['canvasElement']
}

type Renderer = {
  canvasElement: unknown
}
```

### System

```bash
Not applicable
```

**Comment by yannbf** [comment]
Hey @unional! Thanks for the report, I appreciate the question. The test-runner's `getStoryContext` function executes the following:

```ts
window.__STORYBOOK_PREVIEW__.storyStore.loadStory({ storyId: 'your-story-id-from-url-here' })
```

which is a core Storybook API, that resolves to something like this:
<img width="1189" alt="image" src="https://github.com/storybookjs/test-runner/assets/1671563/ad31064e-2b07-4e76-9cd6-ad77c363e7dc">

So I can see that it doesn't match `StoryContext`, but rather `StoryContextForEnhancers`. I'll make a fix for it! But keep in mind that this is mostly a Typescript fix, making the type more true to the actual return values, rather than having canvasElement available.
