### ISSUE TITLE
[bug] `getStoryContext` is missing `playFunction`

### ISSUE THREAD

**Issue by scottnath** [storybookjs/test-runner#441]
**Describe the bug**

When using `getStoryContext` inside of `.storybook/test-runner.js`, the contents of the `play` function do not get included in the output. It is missing when used in both `preVisit` and `postVisit`.

**To Reproduce**

1. Use `getStoryContext` in the `test-runner.[ext]` in `preVisit` and `postVisit` and log the output
2. Run `test-storybook`
3. View logged output
4. `undefined` at `context.playFunction` and `moduleExport.play`

**Expected behavior**
The play function should be included?

**Screenshots**

**System**

```
  System:
    OS: macOS 14.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm <----- active
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.2.1
  npmPackages:
    @storybook/addon-coverage: ^1.0.1 => 1.0.1
    @storybook/addon-essentials: ^8.0.0 => 8.0.0
    @storybook/addon-interactions: ^8.0.0 => 8.0.0
    @storybook/addon-links: ^8.0.0 => 8.0.0
    @storybook/blocks: ^8.0.0 => 8.0.0
    @storybook/html: ^8.0.0 => 8.0.0
    @storybook/html-vite: ^8.0.0 => 8.0.0
    @storybook/test: ^8.0.0 => 8.0.0
    @storybook/test-runner: ^0.17.0 => 0.17.0
    storybook: ^8.0.0 => 8.0.0
```

**Additional context**

Reproduction: https://github.com/scottnath/virtual-screen-reader-storybook/tree/test-runner
Logged output in GitHub actions: https://github.com/scottnath/virtual-screen-reader-storybook/actions/runs/8303334953/job/22727286655

thank you

**Comment by yannbf** [comment]
Hey there @scottnath! The hooks execute in node, and because functions are not serializable, they're therefore not passed over the wire. If you really need access to the play function (or any function from parameters, etc), you will have to execute things in the browser context, which you can do via `page.evaluate`:

```ts
  async preVisit(page, story) {
    const ctx = await getStoryContext(page, story);

    await page.evaluate(async () => {
      // This code will be run in the browser
      const ctx = await getStoryContext(page, story);
      console.log('preVisit context', ctx);
    })
  },
```

<img width="522" alt="image" src="https://github.com/storybookjs/test-runner/assets/1671563/d90d2a6a-e0f3-4ffd-8bf6-f33f82b40993">

I don't recommend accessing or executing the play function there. It will already be executed automatically and if it fails, the tests will fail correctly. Cool idea regarding VSR btw!
